version: "3.6"

services:
    registry:
        image: registry:2
        container_name: local_registry
        ports:
            - "5000:5000"
        environment:
            - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
        volumes:
            - /mnt/nfs:/data
    nginx:
        image: nginx
        container_name: nginx
        #environment:
        #    - NGINX_HOST=registry.jkirn.com
        #    - NGINX_PORT=80
        links:
            - registry:registry
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/server.crt:/etc/nginx/server.crt
            - ./nginx/server.key:/etc/nginx/server.key
            - ./nginx/ca.crt:/etc/nginx/ca.crt
            # - ./htpasswd:/etc/nginx/htpasswd.users
        ports:
            - 5043:443